# Generated by Django 5.2.4 on 2025-07-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="image",
            field=models.ImageField(
                default="profile_images/profile.webp", upload_to="profile_images/"
            ),
        ),
    ]
