# Generated by Django 5.2.4 on 2025-07-17 08:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=cloudinary.models.CloudinaryField(default='profile_images/profile.webp', max_length=255, verbose_name='image'),
        ),
    ]
